plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.4'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.anki'
version = '0.0.1-SNAPSHOT'
description = 'Anki management application'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(24)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    // SQLite JDBC driver
    implementation 'org.xerial:sqlite-jdbc:3.43.0.0'
    // To send plain requests to ankiconnect, without it AnkiConnect blocks java requests
    // Apache HttpClient 4.x
    implementation 'org.apache.httpcomponents:httpclient:4.5.14'
    implementation 'org.springframework.ai:spring-ai-starter-model-openai'
    // Jackson for JSON (if not already present)
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
    implementation 'org.springframework.shell:spring-shell-starter:3.2.4'
}


dependencyManagement {
    imports {
        mavenBom "org.springframework.ai:spring-ai-bom:1.0.1"
    }
}



tasks.named('test') {
	useJUnitPlatform()
}
