[package]
name = "Anki"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8", features = ["json"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
sqlx = { version = "0.8", features = ["sqlite", "runtime-tokio", "tls-rustls", "macros", "migrate"] }
argon2 = "0.5.3"
serde = { version = "1.0.229", features = ["derive"] }
tower-sessions = "0.15.0"
