spring.application.name=Anki
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
openai.base-url=https://api.openai.com/v1
spring.ai.openai.api-key=KEY
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0.4